[project]
name = "sprint"
version = "0.1.1"
description = "Special print utility with color-coded tags and formatting"
authors = ["Tanmay Lad", "Rolando Charles"]
readme = "README.md"
packages = [{include = "app"}]
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
]
